# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile lab8/build.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: ./lab8/dist/
    - name: Check hierarchy
      run: ls lab8/src/
    - name: Generate JavaDoc
      run: javadoc -d lab8/javadoc -sourcepath lab8/src/  lab8/src/*.java -link http://docs.oracle.com/javase/7/docs/api/
